Fix memory leak
pubnative/url-driller-android pull request #6
Opened 2017-01-31 12:06 UTC by RagnarR

* Fix memory leak during `HttpURLConnection` in `doDrill()`
* Add new method for possibility set limit for requests.

2017-01-31 12:17 UTC, anshumansworld requested changes

2017-01-31 12:17 UTC, anshumansworld commented on url_driller/src/main/java/net/pubnative/URLDriller.java
> +                    }
there should be else condition that will call `invokeFail(<>)`, no?

2017-01-31 12:17 UTC, anshumansworld commented on url_driller/src/main/java/net/pubnative/URLDriller.java
> +    /**
I think, you missed to remove/comment unused code. It won't compile.

2017-01-31 12:28 UTC, RagnarR commented on url_driller/src/main/java/net/pubnative/URLDriller.java
> +                    }
make sense 👍

2017-01-31 12:35 UTC, RagnarR commented on url_driller/src/main/java/net/pubnative/URLDriller.java
> +    /**
Looks like was broken during creating PR. 👍

2017-01-31 12:44 UTC, anshumansworld approved these changes
👍

2017-01-31 13:26 UTC, merged

2017-02-06 15:02 UTC, RagnarR commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Refactor URLDriller to handle redirects](https://trello.com/c/NlMY9wUv/27-2-refactor-urldriller-to-handle-redirects)